# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: betterproto/tests/inputs/oneof_default_value_serialization/oneof_default_value_serialization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="betterproto/tests/inputs/oneof_default_value_serialization/oneof_default_value_serialization.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\nbbetterproto/tests/inputs/oneof_default_value_serialization/oneof_default_value_serialization.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto"(\n\x07Message\x12\r\n\x05value\x18\x01 \x01(\x03\x12\x0e\n\x06string\x18\x02 \x01(\t"T\n\rNestedMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12)\n\x15wrapped_message_value\x18\x02 \x01(\x0b\x32\x08.MessageH\x00\x42\x0c\n\nvalue_type"\xdf\x02\n\x04Test\x12\x14\n\nbool_value\x18\x01 \x01(\x08H\x00\x12\x15\n\x0bint64_value\x18\x02 \x01(\x03H\x00\x12\x35\n\x0ftimestamp_value\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x12\x33\n\x0e\x64uration_value\x18\x04 \x01(\x0b\x32\x19.google.protobuf.DurationH\x00\x12)\n\x15wrapped_message_value\x18\x05 \x01(\x0b\x32\x08.MessageH\x00\x12\x36\n\x1cwrapped_nested_message_value\x18\x06 \x01(\x0b\x32\x0e.NestedMessageH\x00\x12\x38\n\x12wrapped_bool_value\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.BoolValueH\x00\x12\x13\n\tstr_value\x18\x65 \x01(\tH\x00\x42\x0c\n\nvalue_typeb\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,
        google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,
        google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,
    ],
)


_MESSAGE = _descriptor.Descriptor(
    name="Message",
    full_name="Message",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="value",
            full_name="Message.value",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="string",
            full_name="Message.string",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=199,
    serialized_end=239,
)


_NESTEDMESSAGE = _descriptor.Descriptor(
    name="NestedMessage",
    full_name="NestedMessage",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="NestedMessage.id",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="wrapped_message_value",
            full_name="NestedMessage.wrapped_message_value",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="value_type",
            full_name="NestedMessage.value_type",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=241,
    serialized_end=325,
)


_TEST = _descriptor.Descriptor(
    name="Test",
    full_name="Test",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="bool_value",
            full_name="Test.bool_value",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="int64_value",
            full_name="Test.int64_value",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="timestamp_value",
            full_name="Test.timestamp_value",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="duration_value",
            full_name="Test.duration_value",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="wrapped_message_value",
            full_name="Test.wrapped_message_value",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="wrapped_nested_message_value",
            full_name="Test.wrapped_nested_message_value",
            index=5,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="wrapped_bool_value",
            full_name="Test.wrapped_bool_value",
            index=6,
            number=7,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="str_value",
            full_name="Test.str_value",
            index=7,
            number=101,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="value_type",
            full_name="Test.value_type",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        ),
    ],
    serialized_start=328,
    serialized_end=679,
)

_NESTEDMESSAGE.fields_by_name["wrapped_message_value"].message_type = _MESSAGE
_NESTEDMESSAGE.oneofs_by_name["value_type"].fields.append(
    _NESTEDMESSAGE.fields_by_name["wrapped_message_value"]
)
_NESTEDMESSAGE.fields_by_name[
    "wrapped_message_value"
].containing_oneof = _NESTEDMESSAGE.oneofs_by_name["value_type"]
_TEST.fields_by_name[
    "timestamp_value"
].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TEST.fields_by_name[
    "duration_value"
].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_TEST.fields_by_name["wrapped_message_value"].message_type = _MESSAGE
_TEST.fields_by_name["wrapped_nested_message_value"].message_type = _NESTEDMESSAGE
_TEST.fields_by_name[
    "wrapped_bool_value"
].message_type = google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE
_TEST.oneofs_by_name["value_type"].fields.append(_TEST.fields_by_name["bool_value"])
_TEST.fields_by_name["bool_value"].containing_oneof = _TEST.oneofs_by_name["value_type"]
_TEST.oneofs_by_name["value_type"].fields.append(_TEST.fields_by_name["int64_value"])
_TEST.fields_by_name["int64_value"].containing_oneof = _TEST.oneofs_by_name[
    "value_type"
]
_TEST.oneofs_by_name["value_type"].fields.append(
    _TEST.fields_by_name["timestamp_value"]
)
_TEST.fields_by_name["timestamp_value"].containing_oneof = _TEST.oneofs_by_name[
    "value_type"
]
_TEST.oneofs_by_name["value_type"].fields.append(_TEST.fields_by_name["duration_value"])
_TEST.fields_by_name["duration_value"].containing_oneof = _TEST.oneofs_by_name[
    "value_type"
]
_TEST.oneofs_by_name["value_type"].fields.append(
    _TEST.fields_by_name["wrapped_message_value"]
)
_TEST.fields_by_name["wrapped_message_value"].containing_oneof = _TEST.oneofs_by_name[
    "value_type"
]
_TEST.oneofs_by_name["value_type"].fields.append(
    _TEST.fields_by_name["wrapped_nested_message_value"]
)
_TEST.fields_by_name[
    "wrapped_nested_message_value"
].containing_oneof = _TEST.oneofs_by_name["value_type"]
_TEST.oneofs_by_name["value_type"].fields.append(
    _TEST.fields_by_name["wrapped_bool_value"]
)
_TEST.fields_by_name["wrapped_bool_value"].containing_oneof = _TEST.oneofs_by_name[
    "value_type"
]
_TEST.oneofs_by_name["value_type"].fields.append(_TEST.fields_by_name["str_value"])
_TEST.fields_by_name["str_value"].containing_oneof = _TEST.oneofs_by_name["value_type"]
DESCRIPTOR.message_types_by_name["Message"] = _MESSAGE
DESCRIPTOR.message_types_by_name["NestedMessage"] = _NESTEDMESSAGE
DESCRIPTOR.message_types_by_name["Test"] = _TEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType(
    "Message",
    (_message.Message,),
    {
        "DESCRIPTOR": _MESSAGE,
        "__module__": "betterproto.tests.inputs.oneof_default_value_serialization.oneof_default_value_serialization_pb2"
        # @@protoc_insertion_point(class_scope:Message)
    },
)
_sym_db.RegisterMessage(Message)

NestedMessage = _reflection.GeneratedProtocolMessageType(
    "NestedMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _NESTEDMESSAGE,
        "__module__": "betterproto.tests.inputs.oneof_default_value_serialization.oneof_default_value_serialization_pb2"
        # @@protoc_insertion_point(class_scope:NestedMessage)
    },
)
_sym_db.RegisterMessage(NestedMessage)

Test = _reflection.GeneratedProtocolMessageType(
    "Test",
    (_message.Message,),
    {
        "DESCRIPTOR": _TEST,
        "__module__": "betterproto.tests.inputs.oneof_default_value_serialization.oneof_default_value_serialization_pb2"
        # @@protoc_insertion_point(class_scope:Test)
    },
)
_sym_db.RegisterMessage(Test)


# @@protoc_insertion_point(module_scope)
