# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extension.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='extension.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x65xtension.proto\x1a google/protobuf/descriptor.proto\"\x1d\n\tMyOptions\x12\x10\n\x08max_size\x18\x01 \x01(\x05:=\n\textension\x12\x1d.google.protobuf.FieldOptions\x18\xf2\x07 \x01(\x0b\x32\n.MyOptions'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


EXTENSION_FIELD_NUMBER = 1010
extension = _descriptor.FieldDescriptor(
  name='extension', full_name='extension', index=0,
  number=1010, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_MYOPTIONS = _descriptor.Descriptor(
  name='MyOptions',
  full_name='MyOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_size', full_name='MyOptions.max_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['MyOptions'] = _MYOPTIONS
DESCRIPTOR.extensions_by_name['extension'] = extension
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyOptions = _reflection.GeneratedProtocolMessageType('MyOptions', (_message.Message,), {
  'DESCRIPTOR' : _MYOPTIONS,
  '__module__' : 'extension_pb2'
  # @@protoc_insertion_point(class_scope:MyOptions)
  })
_sym_db.RegisterMessage(MyOptions)

extension.message_type = _MYOPTIONS
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(extension)

# @@protoc_insertion_point(module_scope)
